# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "portainer/agent:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Portainer Agent"
  org.opencontainers.image.description: ""
  org.opencontainers.image.source: "https://github.com/netadmindave/hassio_addons/tree/main/Portainer_Agent"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
